language: python
python:
    - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: nosetests
env:
    global:
        - consumer_key=""
        - consumer_secret=""
        - access_token=""
        - access_token_secret=""
